# Creating, Concatenating, and Expanding Matrices

In [1]:
A = 100;
whos A

  Name      Size            Bytes  Class     Attributes

  A         1x1                 8  double              




## Constructing a Matrix of Data

In [2]:
A = [12 62 93 -8]


A =

    12    62    93    -8




In [3]:
sz = size(A)


sz =

     1     4




In [5]:
A = [12 62; 93 -8]


A =

    12    62
    93    -8




In [6]:
sz = size(A)


sz =

     2     2




## Specialized Matrix Functions

In [7]:
A = zeros(3,2)


A =

     0     0
     0     0
     0     0




In [8]:
A = ones(2,4)


A =

     1     1     1     1
     1     1     1     1




The [diag](https://www.mathworks.com/help/matlab/ref/diag.html) function places the input elements on the diagonal of a matrix. For example, create a row vector A containing four elements. Then, create a 4-by-4 matrix whose diagonal elements are the elements of A.

In [10]:
A = [12 62 93 -8];
B = diag(A)


B =

    12     0     0     0
     0    62     0     0
     0     0    93     0
     0     0     0    -8




## Concatenating Matrices

In [11]:
A = ones(1,4);
B = zeros(1,4);
C = [A B]


C =

     1     1     1     1     0     0     0     0




To arrange A and B as two rows of a matrix, use the semicolon.

In [12]:
D = [A;B]


D =

     1     1     1     1
     0     0     0     0




To concatenate two matrices, they must have compatible sizes. In other words, when you concatenate matrices horizontally, they must have the same number of rows. When you concatenate them vertically, they must have the same number of columns. For example, horizontally concatenate two matrices that both have two rows.

In [14]:
A = ones(2,3)


A =

     1     1     1
     1     1     1




In [15]:
B = zeros(2,2)


B =

     0     0
     0     0




In [16]:
C = [A B]


C =

     1     1     1     0     0
     1     1     1     0     0




In [17]:
D = horzcat(A, B)


D =

     1     1     1     0     0
     1     1     1     0     0




## Generating a Numeric Sequence

In [18]:
A = 1:10


A =

     1     2     3     4     5     6     7     8     9    10




In [20]:
A = -2.5:2.5


A =

   -2.5000   -1.5000   -0.5000    0.5000    1.5000    2.5000




In [21]:
A = 0:2:10


A =

     0     2     4     6     8    10




In [22]:
A = 6:-1:0


A =

     6     5     4     3     2     1     0




## Expanding a Matrix

In [23]:
A = [10  20  30; 60  70  80]


A =

    10    20    30
    60    70    80




In [24]:
A(3,4) = 1


A =

    10    20    30     0
    60    70    80     0
     0     0     0     1




In [25]:
A(4:5,5:6) = [2 3; 4 5]


A =

    10    20    30     0     0     0
    60    70    80     0     0     0
     0     0     0     1     0     0
     0     0     0     0     2     3
     0     0     0     0     4     5




To expand the size of a matrix repeatedly, such as within a for loop, it's usually best to preallocate space for the largest matrix you anticipate creating. Without preallocation, MATLAB has to allocate memory every time the size increases, slowing down operations. For example, preallocate a matrix that holds up to 10,000 rows and 10,000 columns by initializing its elements to zero.

In [27]:
A = zeros(10000,10000);

## Empty Arrays

An empty array in MATLAB is an array with at least one dimension length equal to zero. Empty arrays are useful for representing the concept of "nothing" programmatically. For example, suppose you want to [find](https://www.mathworks.com/help/matlab/ref/find.html) all elements of a vector that are less than 0, but there are none. The find function returns an empty vector of indices, indicating that it couldn't find any elements less than 0.

In [28]:
A = [1 2 3 4];
ind = find(A<0)


ind =

  1x0 empty double row vector




Many algorithms contain function calls that can return empty arrays. It is often useful to allow empty arrays to flow through these algorithms as function arguments instead of handling them as a special case. If you do need to customize empty array handling, you can check for them using the isempty function.

In [29]:
TF = isempty(ind)


TF =

  logical

   1


