# Creating, Concatenating, and Expanding Matrices

In [1]:
A = 100;
whos A

  Name      Size            Bytes  Class     Attributes

  A         1x1                 8  double              




## Constructing a Matrix of Data

In [2]:
A = [12 62 93 -8]


A =

    12    62    93    -8




In [3]:
sz = size(A)


sz =

     1     4




In [5]:
A = [12 62; 93 -8]


A =

    12    62
    93    -8




In [6]:
sz = size(A)


sz =

     2     2




## Specialized Matrix Functions

In [7]:
A = zeros(3,2)


A =

     0     0
     0     0
     0     0




In [8]:
A = ones(2,4)


A =

     1     1     1     1
     1     1     1     1




The [diag](https://www.mathworks.com/help/matlab/ref/diag.html) function places the input elements on the diagonal of a matrix. For example, create a row vector A containing four elements. Then, create a 4-by-4 matrix whose diagonal elements are the elements of A.

In [10]:
A = [12 62 93 -8];
B = diag(A)


B =

    12     0     0     0
     0    62     0     0
     0     0    93     0
     0     0     0    -8




## Concatenating Matrices

In [11]:
A = ones(1,4);
B = zeros(1,4);
C = [A B]


C =

     1     1     1     1     0     0     0     0




To arrange A and B as two rows of a matrix, use the semicolon.

In [12]:
D = [A;B]


D =

     1     1     1     1
     0     0     0     0




To concatenate two matrices, they must have compatible sizes. In other words, when you concatenate matrices horizontally, they must have the same number of rows. When you concatenate them vertically, they must have the same number of columns. For example, horizontally concatenate two matrices that both have two rows.

In [14]:
A = ones(2,3)


A =

     1     1     1
     1     1     1




In [15]:
B = zeros(2,2)


B =

     0     0
     0     0




In [16]:
C = [A B]


C =

     1     1     1     0     0
     1     1     1     0     0




In [17]:
D = horzcat(A, B)


D =

     1     1     1     0     0
     1     1     1     0     0




## Generating a Numeric Sequence