# Linear Algebra Review

## Matrices

In [3]:
% The ; denotes we are going back to a new row.
A = [1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12];

% Initialize a vector 
v = [1;2;3]; 

% Get the dimension of the matrix A where m = rows and n = columns
[m,n] = size(A);

% You could also store it this way
dim_A = size(A);

% Get the dimension of the vector v 
dim_v = size(v);

% Now let's index into the 2nd row 3rd column of matrix A
A_23 = A(2,3);

% Matrix addition
A = [1 0; 2 5; 3 1]; B = [4 0.5; 2 5; 0 1]; C = A+B;

## Addition and Scalar Matrix Multiplication

In [32]:
% Initialize matrix A and B 
A = [1, 2, 4; 5, 3, 2];
B = [1, 3, 4; 1, 1, 1];

% Initialize constant s 
s = 2;

% See how element-wise addition works
add_AB = A + B ;

% See how element-wise subtraction works
sub_AB = A - B;

% See how scalar multiplication works
mult_As = A * s;

% Divide A by s
div_As = A / s;

% What happens if we have a Matrix + scalar?
add_As = A + s;

mult_As

u=[1; 3; -1]; v = [2; 2; 4];
u'*v


mult_As =

     2     4     8
    10     6     4


ans =

     4




## Matrix Vector Multiplication

- x contains a matrix of house size in square footage $ft^{2}$
- my_hyp is defined as $H_{\theta}(x) = \theta_0 + \theta_1{x}$
    - where $\theta_0$ and $\theta_1$ are my parameters
- $H_{\theta}(x) = -40 + 0.25{x}$

In [4]:
x = [1 2104; 1 1416; 1 1534; 1 852]; my_hyp = [-40 0.25]';
prediction = x * my_hyp;

In [5]:
prediction


prediction =

  486.0000
  314.0000
  343.5000
  173.0000




## Matrix Matrix Multiplication

### An Example
Let's say we have two matrices and I want to multiply them together

In [10]:
A = [1 3 2 ; 4 0 1]; B = [1 3; 0 1; 5 2];
A 
B
A * B


A =

     1     3     2
     4     0     1


B =

     1     3
     0     1
     5     2


ans =

    11    10
     9    14




In [11]:
[1 3; 2 4; 0 5] * [1 0; 2 3]


ans =

     7     9
    10    12
    10    15




## Another Neat Trick with Matrix Matrix Multiplication

Let's say we have four houses whose prices we want to predict.

|House sizes  | 
| :-----------:|
| 2104| 
|1416| 
| 1534| 
| 852| 

We also have three competing hypotheses:

1. $h_{\theta}(x) = -40 + 0.25{x}$
2. $h_{\theta}(x) = 200 + 0.1{x}$
3. $h_{\theta}(x) = -150 + 0.4{x}$

We can apply all three competing hypotheses to the matrix containing houses sizes by using a **matrix matrix multiplication**. 

In [15]:
% Remember from above that x contains matrix of house sizes
x 
% Include additional hypotheses to my_hyp matrix
my_hyp = [-40 200 -150; 0.25 0.1 0.4];
my_hyp
% Matrix multiplication
prediction = round(x * my_hyp);
prediction


x =

           1        2104
           1        1416
           1        1534
           1         852


my_hyp =

  -40.0000  200.0000 -150.0000
    0.2500    0.1000    0.4000


prediction =

   486   410   692
   314   342   416
   344   353   464
   173   285   191




## Using linsolve

In [19]:
prediction = mldivide(x, my_hyp)
prediction

Matrix dimensions must agree.



In [20]:
A = magic(3)


A =

     8     1     6
     3     5     7
     4     9     2




## Properties of Matrix Multiplication

### 1. Matrix multiplication is not commutative

In [21]:
3 * 5 
% The same as
5 * 3


ans =

    15


ans =

    15




It turns out that this commutative property is not true for matrices.

Let $A$ and $B$ be matrices. Then in general,

$A$ * $B$ $\neq$ $B$ * $A$ (**not commutative.**)

It's not ok to just arbitrarily reverse the order in which you multiply matrices.

For example here are two matrices

In [22]:
A = [1 1; 0 0]; B = [0 0; 2 0];
A * B
B * A


ans =

     2     0
     0     0


ans =

     0     0
     2     2




As we can see above, these two matrix multiplications do not yield the same result.

Say, we have two matrices A and B

If matrix A is m * n and,

Matrix B is n * m then,

A * B is m * m but,

B * A is n * n

Also note that A * B and B * A may not be the same dimension even though the same above is a 2 X 2 matrix

### 2. Matrix multiplication is associative

So when talking about scalars or  ${\rm I\!R}$ numbers, let say I have 3 * 5 * 2

I can either multiply 5 * 2 first OR start by multiplying 3 * 5 

This is called the **associative** property of real number multiplication.

Let's say we have three matrices A, B and C

A * (B * C) = (A * B) * C

So we say that matrix multiplication does enjoy the associative property. 

### 3. The identity matrix

So when dealing with scalars or  ${\rm I\!R}$ numbers, the number 1 is **identity**. What mean by this is that for any real number $z$, if we multiply 

- 1 * $z$ = $z$ * 1 = $z$

Denoted $I$ or $I_{n x n}$
- The identity matrix has 1s along the diagonal and 0s everywhere else

Examples of identity matrices:

2 X 2
\begin{bmatrix}
  1 & 0 \\
  0 & 1 \\
 \end{bmatrix}

3 X 3
 \begin{bmatrix}
  1 & 0 & 0\\
  0 & 1 & 0\\
  0 & 0 & 1\\
 \end{bmatrix}

4 X 4
  \begin{bmatrix}
  1 & 0 & 0 & 0\\
  0 & 1 & 0 & 0\\
  0 & 0 & 1 & 0\\
  0 & 0 & 0 & 1\\
 \end{bmatrix}
 
For any matrix $A$,
   - $A$ * $I$ = $I$ * $A$ = $A$

In [23]:
% Initialize random matrices A and B 
A = [1,2;4,5]
B = [1,1;0,2]

% Initialize a 2 by 2 identity matrix
I = eye(2)

% The above notation is the same as I = [1,0;0,1]

% What happens when we multiply I*A ? 
IA = I*A 

% How about A*I ? 
AI = A*I 

% Compute A*B 
AB = A*B 

% Is it equal to B*A? 
BA = B*A 

% Note that IA = AI but AB != BA


A =

     1     2
     4     5


B =

     1     1
     0     2


I =

     1     0
     0     1


IA =

     1     2
     4     5


AI =

     1     2
     4     5


AB =

     1     5
     4    14


BA =

     5     7
     8    10




In [27]:
magic?

 MAGIC  Magic square.
    MAGIC(N) is an N-by-N matrix constructed from the integers
    1 through N^2 with equal row, column, and diagonal sums.
    Produces valid magic squares for all N > 0 except N = 2.

    Reference page in Doc Center
       doc magic




In [25]:
A = eye(2)


A =

     1     0
     0     1




In [33]:
 M = zeros(3,3)


M =

     0     0     0
     0     0     0
     0     0     0




## Linear Algebra Quiz

In [34]:
% Question 1
A = [4 3; 6 9]; B = [-2 9; -5 2];
A - B


ans =

     6    -6
    11     7




In [35]:
% Question 2
x = [2; 7; 4; 1];
3 * x


ans =

     6
    21
    12
     3




In [36]:
% Question 3
u = [8; 1; 4];
u'


ans =

     8     1     4




In [37]:
% Question 4
u = [3; -5; 4]; v = [1; 2; 5];
u'*v


ans =

    13




Let A and B be 3x3 (square) matrices. Which of the following must necessarily hold true? Check all that apply.

- A∗B=B∗A (not correct)
- A*B*A = B*A*B A∗B∗A=B∗A∗B (correct)
- If B is the 3x3 identity matrix, then A * B = B * A A∗B=B∗A (correct)
- If C = A*BC=A∗B, then C is a 3x3 matrix. (correct)